feat: Affiliate and analytics views
starknet-id/affiliate.starknet.id pull request #2
Opened 2023-07-11 18:31 UTC by J4ckyLIM

Note:

Few things are missing:

- Data fetching not done yet --> every data here are mocked
- CTA not working too --> console.log mostly

2023-07-12 09:33 UTC, irisdv requested changes
Great PR ! It looks great :) 
I made some small comments in the code. 

Do you use prettier ? If yes, I think we don't have the same configuration. Could you add a command to format the code with prettier. An example : https://github.com/starknet-id/starknet.id/blob/mainnet/package.json#L11

A few comments on the design integration : 
- There is less space between in this card than in the design on the figma, also the starknet icon is supposed to be colored. Also it seems that some text are not in the right color (I see them black instead of secondary color)
<img width="1095" alt="Capture d’écran 2023-07-12 à 11 00 16" src="https://github.com/starknet-id/affiliate.starknet.id/assets/8224462/39bd4991-a108-424d-80f1-245d411ccb8d">

- At the moment we cannot really see the icons on the call to actions to join discord and download assets, could you get closer to what's on the figma ? 
<img width="410" alt="Capture d’écran 2023-07-12 à 11 02 21" src="https://github.com/starknet-id/affiliate.starknet.id/assets/8224462/3b4f3401-55b6-4059-bb65-76a9b3345c06">
<img width="391" alt="Capture d’écran 2023-07-12 à 11 02 18" src="https://github.com/starknet-id/affiliate.starknet.id/assets/8224462/9dbf1f51-5f61-4d8d-a07d-527f876d9bb9">

- there should be some sort of shadow under the icon with the level number : 
<img width="243" alt="Capture d’écran 2023-07-12 à 10 29 25" src="https://github.com/starknet-id/affiliate.starknet.id/assets/8224462/db51608f-63a4-40c2-9dca-0d6eefff31e4">

- The text "You have earned..." should be in bold (I think it has the wrong font). Also I'm wondering if there should be a bit more space between the menu bar and the content of the page. 
<img width="466" alt="Capture d’écran 2023-07-12 à 11 26 44" src="https://github.com/starknet-id/affiliate.starknet.id/assets/8224462/322ff5a0-ce0b-4e4f-91b2-1a2b065425df">

On mobile : 
- the identicons is supposed to be cut off
<img width="290" alt="Capture d’écran 2023-07-12 à 10 29 07" src="https://github.com/starknet-id/affiliate.starknet.id/assets/8224462/a51b30a2-b1a9-4214-8709-1156ebfc66ab">

- the faq should be ordered a bit differently : align number and icon and under there is the question 
<img width="275" alt="Capture d’écran 2023-07-12 à 10 29 17" src="https://github.com/starknet-id/affiliate.starknet.id/assets/8224462/770d19ae-c7b6-430a-ad36-80389376bc64">

2023-07-12 09:33 UTC, irisdv commented on components/UI/experienceBar.tsx
> +import helper from "../../styles/components/helper.module.css";
helper is not used in this component

2023-07-12 09:33 UTC, irisdv commented on components/UI/identitySection.tsx
> +import helper from "../../styles/components/helper.module.css";
Not used in component as well

2023-07-12 09:33 UTC, irisdv commented on components/UI/levelSection.tsx
> +import helper from "../../styles/components/helper.module.css";
same

2023-07-12 09:33 UTC, irisdv commented on components/UI/navbar.tsx
>  import SelectNetwork from "./selectNetwork";
SelectNetwork is not used

2023-07-12 09:33 UTC, irisdv commented on components/UI/navbar.tsx
> +                <li className="text-default font-bold">Affiliate Space</li>
Menu items should use `Poppins-Bold` instead of Poppins-Regular and I think in the figma it uses the secondary color instead of black

2023-07-12 17:40 UTC, J4ckyLIM commented on components/UI/navbar.tsx
> +                <li className="text-default font-bold">Affiliate Space</li>
Yep you're right

2023-07-12 17:54 UTC, J4ckyLIM commented
Few comments about you say:

For some reason the text appears in the right color to me see below:

<img width="841" alt="Capture d’écran 2023-07-12 à 19 53 23" src="https://github.com/starknet-id/affiliate.starknet.id/assets/42095148/f6a2d046-a947-4615-b1b1-8508aec68136">

Same for the "you have earned..." unless I have to use "Poppins-Bold" ?

2023-07-13 08:39 UTC, irisdv commented
Thanks for the updates ! 
Yes I think "you have earned..." is supposed to use "Poppins-Bold"

One last comment. On mobile right now we have this : 
<img width="429" alt="Capture d’écran 2023-07-13 à 10 25 30" src="https://github.com/starknet-id/affiliate.starknet.id/assets/8224462/071bfcbb-62f3-4bcb-8f5c-519ec1633ddf">

Could you add more spaces between the domain title and text and also get closer to what we have on figma for the identicon (the random character associated to a .stark domain)
<img width="199" alt="Capture d’écran 2023-07-13 à 10 25 11" src="https://github.com/starknet-id/affiliate.starknet.id/assets/8224462/c1bef7be-06f3-48ce-b1c2-4bf83cc2ef88">


About the build errors, I think once you cleanup the unused code in the repo, the errors will be solved and we'll be able to test the build and check the colors of the titles because mine are still black.

2023-07-19 10:10 UTC, irisdv approved these changes
lgtm

2023-07-27 17:21 UTC, merged