Fix Stark Affiliate section
starknet-id/affiliate.starknet.id pull request #29
Opened 2024-11-23 11:47 UTC by wheval

Closes #20

2024-11-23 13:41 UTC, fricoben requested changes
change this to a confirm with a little green tick

<img width="101" alt="Capture d’écran 2024-11-23 à 21 40 59" src="https://github.com/user-attachments/assets/84f67cb0-c235-4674-8445-c4393ae7d2f5">

2024-11-23 13:41 UTC, fricoben commented on components/UI/affiliateLink.tsx
> +  const linkToShow = `https://app.starknet.id/${domain}`;
keep it :)

2024-11-23 13:45 UTC, wheval commented on components/UI/affiliateLink.tsx
> +  const linkToShow = `https://app.starknet.id/${domain}`;
okay!

2024-11-23 14:53 UTC, wheval commented
@fricoben. Please review

2024-11-25 01:10 UTC, fricoben approved these changes
lgtm

2024-11-25 01:10 UTC, merged