Fix 26
starknet-id/affiliate.starknet.id pull request #30
Opened 2024-11-23 23:11 UTC by Michaelkingsdev

Fixes #26 

# Before
![image](https://github.com/user-attachments/assets/9fe9b0f9-fe49-4868-8293-ccd010cb30f4)

# After

2024-11-23 23:20 UTC, Michaelkingsdev commented
@fricoben 
please review and give corrections. Thanks

2024-11-24 06:23 UTC, fricoben requested changes
- [ ] Background color is not the same 
- [ ] The image introduces a scroll on laptop (we don't want that). 
- [ ] Section isn't centered

Please take example on this page https://app.starknet.id/qsd

2024-11-24 07:08 UTC, Michaelkingsdev commented
> * [ ]  Background color is not the same
> * [ ]  The image introduces a scroll on laptop (we don't want that).
> * [ ]  Section isn't centered
> 
> Please take example on this page https://app.starknet.id/qsd

Alright. Thanks

2024-11-24 07:12 UTC, Michaelkingsdev commented
> > * [ ]   Background color is not the same
> > * [ ]   The image introduces a scroll on laptop (we don't want that).
> > * [ ]   Section isn't centered
> > 
> > Please take example on this page https://app.starknet.id/qsd
> 
> Alright. Thanks

@fricoben 
This link:  https://app.starknet.id/qsd is not accessible.

2024-11-25 01:11 UTC, fricoben commented
> > > * [ ]    Background color is not the same
> > > * [ ]    The image introduces a scroll on laptop (we don't want that).
> > > * [ ]    Section isn't centered
> > > 
> > > Please take example on this page https://app.starknet.id/qsd
> > 
> > 
> > Alright. Thanks
> 
> @fricoben This link: https://app.starknet.id/qsd is not accessible.

1. It's a 404 page to give you example
2. yes it's eccessible

2024-11-25 06:53 UTC, Michaelkingsdev commented
> > > > * [ ]     Background color is not the same
> > > > * [ ]     The image introduces a scroll on laptop (we don't want that).
> > > > * [ ]     Section isn't centered
> > > > 
> > > > Please take example on this page https://app.starknet.id/qsd
> > > 
> > > 
> > > Alright. Thanks
> > 
> > 
> > @fricoben This link: https://app.starknet.id/qsd is not accessible.
> 
> 1. It's a 404 page to give you example
> 2. yes it's eccessible

![image](https://github.com/user-attachments/assets/e7ee5e1e-dc10-40e9-b04f-2c498c6fb93e)

2024-11-25 07:16 UTC, fricoben commented
> > > > > * [ ]      Background color is not the same
> > > > > * [ ]      The image introduces a scroll on laptop (we don't want that).
> > > > > * [ ]      Section isn't centered
> > > > > 
> > > > > Please take example on this page https://app.starknet.id/qsd
> > > > 
> > > > 
> > > > Alright. Thanks
> > > 
> > > 
> > > @fricoben This link: https://app.starknet.id/qsd is not accessible.
> > 
> > 
> > 
> > 1. It's a 404 page to give you example
> > 2. yes it's eccessible
> 
> ![image](https://private-user-images.githubusercontent.com/125934142/389408313-e7ee5e1e-dc10-40e9-b04f-2c498c6fb93e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTkyNjksIm5iZiI6MTczMjUxODk2OSwicGF0aCI6Ii8xMjU5MzQxNDIvMzg5NDA4MzEzLWU3ZWU1ZTFlLWRjMTAtNDBlOS1iMDRmLTJjNDk4YzZmYjkzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNzE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjEwOWM0Y2ZkMzJkNThhNjQ4NGYxYzBiMDk1YjYyNmU4Y2I0ZjBmYzk2MDI4ZWExNzk4MDQ4NGMyZDlkYWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GA9XQwgdqURpZiJ2vY6pYo2VaT6MloYNGRWVLQ97auM)

You have a problem on your laptop or network it seems, please use another device/network

2024-11-25 08:33 UTC, Michaelkingsdev commented
> > > > > > * [ ]       Background color is not the same
> > > > > > * [ ]       The image introduces a scroll on laptop (we don't want that).
> > > > > > * [ ]       Section isn't centered
> > > > > > 
> > > > > > Please take example on this page https://app.starknet.id/qsd
> > > > > 
> > > > > 
> > > > > Alright. Thanks
> > > > 
> > > > 
> > > > @fricoben This link: https://app.starknet.id/qsd is not accessible.
> > > 
> > > 
> > > 
> > > 1. It's a 404 page to give you example
> > > 2. yes it's eccessible
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/125934142/389408313-e7ee5e1e-dc10-40e9-b04f-2c498c6fb93e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTkyNjksIm5iZiI6MTczMjUxODk2OSwicGF0aCI6Ii8xMjU5MzQxNDIvMzg5NDA4MzEzLWU3ZWU1ZTFlLWRjMTAtNDBlOS1iMDRmLTJjNDk4YzZmYjkzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNzE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjEwOWM0Y2ZkMzJkNThhNjQ4NGYxYzBiMDk1YjYyNmU4Y2I0ZjBmYzk2MDI4ZWExNzk4MDQ4NGMyZDlkYWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GA9XQwgdqURpZiJ2vY6pYo2VaT6MloYNGRWVLQ97auM)
> 
> You have a problem on your laptop or network it seems, please use another device/network

Hello @fricoben 
Can you send a screenshot of that page. I think its better that way. i cant access it from my end.

2024-11-25 09:03 UTC, Michaelkingsdev commented
@fricoben  Done
![image](https://github.com/user-attachments/assets/e29dd9f6-b693-437e-ac59-357471cd4b53)

2024-11-26 01:50 UTC, fricoben approved these changes
lgtm

2024-11-26 01:51 UTC, fricoben requested changes
Don't forget the uppercase ! Test the build after sending PR

2024-11-26 01:51 UTC, fricoben commented on pages/error.tsx
> +            src="/visuals/errorillu.webp"
NO `errorIllu.web` don't forget the uppercase

2024-11-26 10:32 UTC, Michaelkingsdev commented
@fricoben 
Done Sir

2024-11-27 01:34 UTC, fricoben requested changes
<img width="1426" alt="Capture d’écran 2024-11-27 à 09 34 04" src="https://github.com/user-attachments/assets/20144f70-cfc3-4d3b-92f7-fe2dad40b20b">

Your PR completely destroys the rest of the website here, pls fix and TEST before sending your PR

2024-11-27 13:44 UTC, fricoben commented
@Michaelkingsdev PLS fix

2024-11-27 15:29 UTC, Michaelkingsdev commented
> @Michaelkingsdev PLS fix

Alright sir

2024-11-27 22:44 UTC, Michaelkingsdev commented
@fricoben Are you this is not how the page looks?
I recloned the repo and the page still looks the same. Should i fix it by the way. 
![image](https://github.com/user-attachments/assets/93089fdb-6340-43dc-ac20-e0392e79f990)

2024-11-28 01:51 UTC, fricoben approved these changes
lgtm

2024-11-28 01:52 UTC, merged