fix: display starkName
starknet-id/affiliate.starknet.id pull request #34
Opened 2024-12-11 20:08 UTC by NueloSE

Closes #24

2024-12-11 20:12 UTC, NueloSE commented
![demo](https://github.com/user-attachments/assets/f4ce6e7b-2ac1-4f89-bb47-6465c10deb0a)

2024-12-12 07:39 UTC, Marchand-Nicolas requested changes
I don't see my pfp

2024-12-12 07:46 UTC, Marchand-Nicolas requested changes
<img width="896" alt="image" src="https://github.com/user-attachments/assets/c53858af-6c14-42f7-83f2-7c7ff68e42cd" />

2024-12-12 07:47 UTC, Marchand-Nicolas requested changes
You can check on our other repos to see how it works, e.g.: https://github.com/lfglabs-dev/app.starknet.id

2024-12-19 15:56 UTC, NueloSE commented
![screenshot12](https://github.com/user-attachments/assets/4b8980fd-a479-4ad7-b5fa-f6eb0a1a91a7)


ready for review @Marchand-Nicolas

2024-12-19 18:02 UTC, Marchand-Nicolas requested changes

2024-12-19 18:02 UTC, Marchand-Nicolas commented on hooks/useNotificationManager.ts
> +  const [notifications, setNotifications] = useAtom(notificationsAtom);
Are you sure you need jotai and useAtom ? Can't you do the same with useState from React ?

2024-12-21 10:01 UTC, Marchand-Nicolas approved these changes
Really good job lgtm!

2024-12-21 10:01 UTC, merged